### ISSUE TITLE
Change camera order

### ISSUE THREAD

**Issue by thiagobones** [trevos3d/K1-USB-Cam#5]
How can you setup the camera that is on "stream" and "stream_1"?
I use my usb camera for spool monitoring and since it takes the place of the "stream" camera, i can't get CP or timelapse to get the "Stream_1" camera as my main camera...is there any way to swap them on the script? thanks!

**Comment by PeterVRC** [comment]
You need to alter the stream in the moonraker.conf file.  Change it from stream to stream_1, or vice-versa, to get the camera you want to use. I am not sure why it totally ignores the Fluidd camera choice for Timelapse in there ( you can choose your camera to use there, but it won't obey that anyway!), but it uses the other values you choose in there (FPS, Constant Rate etc etc).

It would also be good to have a macro call to run the 1 or 2 camera script, as it seems you can run them at any time (via SSH) and they DO change the camera setup. eg If you unplug the USB camera you MUST go back to the single camera, via the single camera script.  I umplug my USB extra camera quite often, so that is a pain to do via SSH each time, for now.....
